
import CONEXION.conexion_Oracle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSetMetaData;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Personal
 */
public class TipoDeInstructor extends javax.swing.JFrame {

    conexion_Oracle con = new conexion_Oracle();
    Connection cn = con.conectar();

    public TipoDeInstructor() throws SQLException {
        initComponents();
        setTitle("Tipo de Instructor");
        setLocationRelativeTo(rootPane);
        setResizable(false);
        mostrarTipoInstructor();
    }

    void mostrarTipoInstructor() throws SQLException {
        
        
        
        DefaultTableModel modelo = new DefaultTableModel();

        
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        modelo.addColumn("Descripcion");
        TipoInstructor.setModel(modelo);

        String sql = "{CALL SPINSTRUCTORES()}";
        CallableStatement cs = cn.prepareCall(sql);
//        cs.executeQuery();
        String datos[] = new String[5];
        try {
//            st = cn.createStatement();
            ResultSet rs = cs.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
            TipoInstructor.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(HorarioGym.class.getName()).log(Level.SEVERE, null, ex);
        }

//
//        modelo.addColumn("Nombre");
//        modelo.addColumn("Apellido");
//        modelo.addColumn("Telefono");
//        modelo.addColumn("Email");
//        modelo.addColumn("Descripcion");
//
//        TipoInstructor.setModel(modelo);
//
//        CallableStatement cs = cn.prepareCall("{call SPINSTRUCTORES}");
//        cs.execute();
//        ResultSet rs = (ResultSet) cs.getObject(1);
//        while (rs.next()) {
//           
//            
//            String nombre = rs.getString("NOMBRE");
//            String apellido = rs.getString("APELLIDO");
//            String telefono = rs.getString("TELEFONO");
//            String email = rs.getString("EMAIL");
//            String descripcion = rs.getString("DESCRIPCION");
//            modelo.addRow(new Object[]{nombre, apellido, telefono, email, descripcion});
//
//
//        }TipoInstructor.setModel(modelo);
//        rs.close();
//        cs.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TipoInstructor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TipoInstructor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TipoInstructor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoDeInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoDeInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoDeInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoDeInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TipoDeInstructor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TipoDeInstructor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TipoInstructor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
